In [102]:
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.tree import DecisionTreeClassifier

In [103]:
df = sns.load_dataset("titanic")

In [104]:
df.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

### **Data Cleaning**

In [105]:
# Remove un necessary columns

df.drop(columns=['who','deck','embark_town','alive', 'alone'],inplace=True)

In [106]:
df.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

   adult_male  
0        True  
1       False  
2       False  
3       False  
4        True

In [107]:
# Step 1 -> train/test/split
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=['survived']),
                                                 df['survived'],
                                                 test_size=0.2,
                                                random_state=42)

In [108]:
X_train.head(2)

pclass   sex   age  sibsp  parch  fare embarked   class  adult_male
331       1  male  45.5      0      0  28.5        S   First        True
733       2  male  23.0      0      0  13.0        S  Second        True

In [109]:
y_train.head()

331    0
733    0
382    0
704    0
813    0
Name: survived, dtype: int64

In [110]:
# Check Null Values

df.isnull().sum()

survived        0
pclass          0
sex             0
age           177
sibsp           0
parch           0
fare            0
embarked        2
class           0
adult_male      0
dtype: int64

### **Fill Nulls using Imputer**

In [111]:
# Applying imputation

si_age = SimpleImputer()
si_embarked = SimpleImputer(strategy='most_frequent')

X_train_age = si_age.fit_transform(X_train[['age']])
X_train_embarked = si_embarked.fit_transform(X_train[['embarked']])

X_test_age = si_age.transform(X_test[['age']])
X_test_embarked = si_embarked.transform(X_test[['embarked']])

In [112]:
df.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

   adult_male  
0        True  
1       False  
2       False  
3       False  
4        True

###  **One Hot Encoding for each categorical feature**


In [113]:

ohe_sex = OneHotEncoder(sparse=False, handle_unknown='ignore')
ohe_embarked = OneHotEncoder(sparse=False, handle_unknown='ignore')
ohe_class = OneHotEncoder(sparse=False, handle_unknown='ignore')
ohe_adult_male = OneHotEncoder(sparse=False, handle_unknown='ignore')

# Fit and transform the training data 
X_train_sex = ohe_sex.fit_transform(X_train[['sex']])
X_train_embarked = ohe_embarked.fit_transform(X_train[['embarked']])
X_train_class = ohe_class.fit_transform(X_train[['class']])
X_train_adult_male = ohe_adult_male.fit_transform(X_train[['adult_male']])

# Transform the test data using the fitted encoders
X_test_sex = ohe_sex.transform(X_test[['sex']])
X_test_embarked = ohe_embarked.transform(X_test[['embarked']])
X_test_class = ohe_class.transform(X_test[['class']])
X_test_adult_male = ohe_adult_male.transform(X_test[['adult_male']])


c:\Users\Dell\miniconda3\envs\pandas_env\Lib\site-packages\sklearn\preprocessing\_encoders.py:975: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
c:\Users\Dell\miniconda3\envs\pandas_env\Lib\site-packages\sklearn\preprocessing\_encoders.py:975: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
c:\Users\Dell\miniconda3\envs\pandas_env\Lib\site-packages\sklearn\preprocessing\_encoders.py:975: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
c:\Users\Dell\miniconda3\envs\pandas_env\Lib\site-packages\sklearn\preprocessing\_encoders.py:975: FutureWarning: `sparse` was rename

In [114]:
X_test_adult_male

array([[0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.

In [115]:
X_train_embarked

array([[0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       ...,
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.]])

In [116]:
X_train.head(2)

pclass   sex   age  sibsp  parch  fare embarked   class  adult_male
331       1  male  45.5      0      0  28.5        S   First        True
733       2  male  23.0      0      0  13.0        S  Second        True

In [117]:
# Rmoving columns because we have already encoded them

X_train_rem = X_train.drop(columns=['sex','age','embarked', 'class', 'adult_male'])

X_test_rem = X_test.drop(columns=['sex','age','embarked', 'class', 'adult_male'])

In [118]:
# Concatenate the dataframes
import numpy as np

X_train_transformed = np.concatenate((X_train_rem, X_train_age, X_train_sex, X_train_embarked, X_train_class, X_train_adult_male), axis=1)
X_test_transformed = np.concatenate((X_test_rem, X_test_age, X_test_sex, X_test_embarked, X_test_class, X_test_adult_male), axis=1)


In [119]:
X_test_transformed.shape

(179, 16)

### **Apply ML Model**

In [120]:
model = DecisionTreeClassifier()
model.fit(X_train_transformed,y_train)

DecisionTreeClassifier()

### **Make Prediction on Test Data**

In [121]:
y_pred = model.predict(X_test_transformed)
y_pred

array([0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 1, 0], dtype=int64)

### **Check Accuracy**

In [122]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.7597765363128491

### **Saving Trained Model Model**

In [123]:
import pickle
pickle.dump(ohe_sex,open('ohe_sex.pkl','wb'))
pickle.dump(ohe_embarked,open('ohe_embarked.pkl','wb'))
pickle.dump(ohe_class,open('ohe_class.pkl','wb'))
pickle.dump(ohe_adult_male,open('ohe_adult_male.pkl','wb'))
pickle.dump(model,open('model.pkl','wb'))

----
----

# **Load  & Make Prediction Using Trained Model**

In [124]:
ohe_sex = pickle.load(open('ohe_sex.pkl','rb'))
ohe_embarked = pickle.load(open('ohe_embarked.pkl','rb'))
ohe_class = pickle.load(open('ohe_class.pkl','rb'))
ohe_adult_male= pickle.load(open('ohe_adult_male.pkl', 'rb'))
model = pickle.load(open('model.pkl','rb'))

### **User Input**

In [125]:
input = np.array([3, 'male', 22.0, 1, 0, 7.2500, 'S', 'Third', True], dtype=object).reshape(1, -1)

### **Transforms the Data using fitted OneHoteEncoder**

In [126]:
input_encoded = np.concatenate((
    input[:, [0, 2, 3, 4, 5]],  # Non-categorical variables
    ohe_sex.transform(input[:, [1]]),
    ohe_embarked.transform(input[:, [6]]),
    ohe_class.transform(input[:, [7]]),
    ohe_adult_male.transform(input[:, [8]])
), axis=1)


c:\Users\Dell\miniconda3\envs\pandas_env\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(
c:\Users\Dell\miniconda3\envs\pandas_env\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(
c:\Users\Dell\miniconda3\envs\pandas_env\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(
c:\Users\Dell\miniconda3\envs\pandas_env\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


### **Prediction**

In [127]:
# Predict
model.predict(input_encoded)

array([0], dtype=int64)